version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: healthchain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthchain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

volumes:
  postgres_data: 