/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { MedicalRecords } from "./MedicalRecords";
export * as factories from "./factories";
export { AccessControl__factory } from "./factories/AccessControl__factory";
export { MedicalRecords__factory } from "./factories/MedicalRecords__factory";
